services:
  #! nginx
  nginx:
    image: "nginx:latest"
    depends_on:
      flask_app:
        condition: service_started
      dashboard:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
    container_name: nginx
    ports:
      - "8080:8080"
    networks:
      - main
  #! API Global
  flask_app:
    build: backend/
    networks:
      - main
  connector:
    image: "jobber:lastest"
    build: connector/
    networks:
      - main
    volumes:
      - ./connector/.jobber:/home/jobberuser/.jobber
    
  mock:
    build: mock_ms/
    networks:
      - main
  #! DASHBOARD
  dashboard:
    build: dashboard/
    depends_on:
      flask_app:
        condition: service_started
    ports:
      - 3000:3000
    networks:
      - main

networks:
  main:
