services:
  #! nginx
  nginx:
    image: "nginx:latest"
    depends_on:
      flask_app:
        condition: service_started
      dashboard:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
    container_name: nginx
    ports:
      - "8080:8080"
    networks:
      - main
  #! API Global
  flask_app:
    build: backend/
    environment:
      - DEBUG=true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - main

  #! MySQL
  mysql:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vivo
    volumes:
      - "./backend/tables.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - 3306:3306
    networks:
      - main
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  #! DASHBOARD
  dashboard:
    build: dashboard/
    depends_on:
      flask_app:
        condition: service_started
    networks:
      - main

networks:
  main:
