-- CONTAINS THE NAME | URL RELATIONSHIP
CREATE TABLE IF NOT EXISTS APIs(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cliente VARCHAR(255),
    produto VARCHAR(255),
    API VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DBs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    URL VARCHAR(255),
    status VARCHAR(255) DEFAULT "UNKNOWN"
);